location /auth/ {

    limit_req zone=api_limit burst=20;

    proxy_pass http://127.0.0.1:5001/;

    proxy_set_header Host $host;
    proxy_set_header Authorization $http_authorization;

}

# location /users/ {

#     proxy_pass http://user_service;

#     proxy_set_header Host $host;
#     proxy_set_header Authorization $http_authorization;

# }

location /buy-rent/ {

    proxy_pass http://buy_rent_service;

    proxy_set_header Host $host;
    proxy_set_header Authorization $http_authorization;

}

# location /chat/ {

#     proxy_pass http://chat_service;

#     proxy_set_header Host $host;
#     proxy_set_header Authorization $http_authorization;

# }

# location /notification/ {

#     proxy_pass http://notification_service;

#     proxy_set_header Host $host;
#     proxy_set_header Authorization $http_authorization;

# }