export const colleges = [
  // IITs
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT BHU Varanasi",
  "IIT Indore",
  "IIT Ropar",
  "IIT Gandhinagar",
  "IIT Patna",
  "IIT Mandi",
  "IIT Bhubaneswar",
  "IIT Jodhpur",
  "IIT Tirupati",
  "IIT Palakkad",
  "IIT Dharwad",
  "IIT Jammu",
  "IIT Goa",

  // NITs
  "NIT Trichy",
  "NIT Surathkal",
  "NIT Warangal",
  "NIT Rourkela",
  "NIT Calicut",
  "NIT Kurukshetra",
  "NIT Durgapur",
  "NIT Allahabad (MNNIT)",
  "NIT Jaipur (MNIT)",
  "NIT Bhopal (MANIT)",
  "NIT Nagpur (VNIT)",
  "NIT Silchar",
  "NIT Jamshedpur",
  "NIT Hamirpur",
  "NIT Raipur",
  "NIT Patna",
  "NIT Srinagar",
  "NIT Agartala",
  "NIT Arunachal Pradesh",
  "NIT Meghalaya",
  "NIT Mizoram",
  "NIT Sikkim",

  // IIITs
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "IIIT Allahabad",
  "IIIT Gwalior",
  "IIIT Jabalpur",
  "IIIT Kancheepuram",
  "IIIT Pune",
  "IIIT Lucknow",
  "IIIT Kota",
  "IIIT Nagpur",
  "IIIT Dharwad",
  "IIIT Bhagalpur",
  "IIIT Bhopal",

  // Top Private Universities
  "BITS Pilani",
  "BITS Goa",
  "BITS Hyderabad",
  "VIT Vellore",
  "VIT Chennai",
  "SRM Institute of Science and Technology",
  "Amrita Vishwa Vidyapeetham",
  "Manipal Institute of Technology",
  "Thapar Institute of Engineering and Technology",
  "Shiv Nadar University",
  "Ashoka University",

  // Major State / Popular Colleges
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "College of Engineering Pune (COEP)",
  "Veermata Jijabai Technological Institute (VJTI)",
  "PES University Bangalore",
  "RV College of Engineering Bangalore",
  "BMS College of Engineering Bangalore",
  "MS Ramaiah Institute of Technology",
  "MIT World Peace University Pune",
  "Sardar Patel Institute of Technology Mumbai",
  "DAIICT Gandhinagar",
];